name: waterqualitymonitoring
description: A water quality monitoring app in Flutter.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase packages
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.4.10

  # Utils
  geolocator: ^13.0.1

  # For image picking and processing
  image_picker: ^0.8.7+4
  image: ^4.1.3

  # TensorFlow Lite inference
  tflite_flutter: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  intl: ^0.18.1

flutter:
  uses-material-design: true
  assets:
    - assets/water_quality_model.tflite
