// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0IWsoS7_iTPBF-d5dKJCTa6wLrOCfYVI',
    appId: '1:943850444661:web:9947a29e18bbc0133d653c',
    messagingSenderId: '943850444661',
    projectId: 'water-qualitymonitoring',
    authDomain: 'water-qualitymonitoring.firebaseapp.com',
    storageBucket: 'water-qualitymonitoring.appspot.com', // ✅ fixed
    measurementId: 'G-5BJ91FF1DM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB28UMwkcBJpGGQj5wpt0YMnK9h0zCWOtw',
    appId: '1:943850444661:android:8d965aace2d1f9c13d653c',
    messagingSenderId: '943850444661',
    projectId: 'water-qualitymonitoring',
    storageBucket: 'water-qualitymonitoring.appspot.com', // ✅ fixed
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqsYcfSx9817qt7QN9k2li5mGMxv3r1vg',
    appId: '1:943850444661:ios:7e27f0f372df5bac3d653c',
    messagingSenderId: '943850444661',
    projectId: 'water-qualitymonitoring',
    storageBucket: 'water-qualitymonitoring.appspot.com', // ✅ fixed
    iosBundleId: 'com.example.waterqualitymonitoring',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqsYcfSx9817qt7QN9k2li5mGMxv3r1vg',
    appId: '1:943850444661:ios:7e27f0f372df5bac3d653c',
    messagingSenderId: '943850444661',
    projectId: 'water-qualitymonitoring',
    storageBucket: 'water-qualitymonitoring.appspot.com', // ✅ fixed
    iosBundleId: 'com.example.waterqualitymonitoring',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0IWsoS7_iTPBF-d5dKJCTa6wLrOCfYVI',
    appId: '1:943850444661:web:e38dca321f5129003d653c',
    messagingSenderId: '943850444661',
    projectId: 'water-qualitymonitoring',
    authDomain: 'water-qualitymonitoring.firebaseapp.com',
    storageBucket: 'water-qualitymonitoring.appspot.com', // ✅ fixed
    measurementId: 'G-0M6SCEK7JE',
  );
}
